services:
    grafana:
        image: grafana/grafana-oss:latest
        container_name: grafana
        user: "${UID}:${GID}"  # 현재 사용자의 UID와 GID로 설정
        #restart: unless-stopped
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./config/grafana/provisioning/:/etc/grafana/provisioning/
            - ~/.evc/grafana:/var/lib/grafana
