---
- name: Deploy Remediation
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: Remediate server
      condition: event.payload.message == "Remediation1"
      action:
        run_playbook:
          name: myplaybook.yml