- name: NFS Models Directory Mount
  hosts: nfs_client
  tasks:
   - name: Make Model Directory
     become: yes
     shell: mkdir -p /models

   - name: Change Permission of the Models Directory
     become: yes
     shell: chown {{ ansible_user }}:{{ ansible_user }} /models

   - name: Automated mount configuration during boot
     become: yes
     shell: echo "{{ nfs_server_ip }}:/models /models nfs defaults,retrans=3,_netdev" | sudo tee -a /etc/fstab

   - name: Mount NFS Server
     become: yes
     shell: mount -t nfs -o vers=4 {{ nfs_server_ip }}:/models /models
