variable "cluster_prefix" {}
variable "cluster_sg_id" {}
variable "worker_node_number" {}
variable "instance_type" {}
variable "vpc" {}
variable "public_subnet_ids" {}
variable "debian_ami" {}
variable "ec2_instance_profile" {}
variable "key_name" {}
variable "public_subnet" {}
variable "architecture" {}